Pin our base image to debian stretch
trussworks/circleci-docker-primary pull request #24
Opened 2019-03-28 23:20 UTC by chrisgilmerproj

Per the [CircleCi Images Best Practices](https://circleci.com/docs/2.0/circleci-images/#best-practices) we ought to be as specific as possible with our image.  

> For example, add `-jessie` or `-stretch` to the end of each of those containers to ensure you’re only using that version of the Debian base OS. Pin down those images to a specific point version, like `circleci/ruby:2.3.7-jessie`, or specify the OS version with `circleci/ruby:2.3-jessie`. Specifying the version is possible for any of the CircleCI images.

2019-04-01 20:28 UTC, pjdufour-truss requested changes
Could you we actually use the `circleci/python:3.7-stretch-node` image instead of installing node ourselves?

https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.3-stretch/node/Dockerfile

2019-04-01 20:51 UTC, chrisgilmerproj commented
> Could you we actually use the `circleci/python:3.7-stretch-node` image instead of installing node ourselves?
> 
> https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.3-stretch/node/Dockerfile

I like this idea! Let me update the PR.

2019-04-01 20:55 UTC, chrisgilmerproj commented
Thanks to @pjdufour-truss 's comment we can get Node and Yarn for free from CircleCI.  I think that's a much better solution than maintaining ourselves.

2019-04-01 20:57 UTC, brainsik commented
What version of Node is now on the image?

2019-04-01 23:54 UTC, chrisgilmerproj commented
The new image will be:
- Node: 10.15.3
- Yarn: 1.13.0

Currently we have:
- Node: 10.15.3
- Yarn: 1.15.2

So this would be a no-op for Node. But would be a downgrade on yarn.

2019-04-02 00:17 UTC, brainsik commented
> So this would be a no-op for Node. But would be a downgrade on yarn.

So, having Yarn drift away from the Homebrew install is the opposite direction I'd like us to move in. The idea here was to try to keep things close so that CI doesn't drift from local.

As for Node, I'm a little surprised to hear that MilMove has pinned to 0.10.x. Is that right? Are they not on the 0.11.x series now?

2019-04-02 16:14 UTC, chrisgilmerproj commented
> So, having Yarn drift away from the Homebrew install is the opposite direction I'd like us to move in. The idea here was to try to keep things close so that CI doesn't drift from local.

Agreed. We could still install Yarn ourselves.

> As for Node, I'm a little surprised to hear that MilMove has pinned to 0.10.x. Is that right? Are they not on the 0.11.x series now?

Homebrew node is currently `v11.12.0`.  I think we've always been on `v10.X` in our circleci containers though.  It would be ideal to have it brought up to the more recent version.

Does anyone else wish that CircleCI's automated docker builds would just do this for us?

2019-04-02 16:16 UTC, chrisgilmerproj commented
My current thinking: Just use `FROM circleci/python:3.7-stretch` and then upgrade Node and upgrade Yarn to match Homebrew. Then add a script to the MilMove pre-commits that checks node and yarn major/minor versions.

2019-04-30 22:16 UTC, chrisgilmerproj commented
I've just pinned this to `stretch` instead of `stretch-node` and left everything else the same.

2019-04-30 22:17 UTC, merged